title: Horror
updated_by: cc2b5d8f-acaa-4ef2-8192-637bc0bdfd02
updated_at: 1617612847
blueprint: genres
hero_image: movies/hero-images/man-s-hand-in-shallow-focus-and-grayscale-photography-167964(1).jpg
